#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : flake8-deprecated
Version  : 1.3
Release  : 8
URL      : https://files.pythonhosted.org/packages/28/28/d39539c84cfb432d7431255ed16f93125342ced4a137d653b50b621fae36/flake8-deprecated-1.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/28/28/d39539c84cfb432d7431255ed16f93125342ced4a137d653b50b621fae36/flake8-deprecated-1.3.tar.gz
Summary  : Warns about deprecated method calls.
Group    : Development/Tools
License  : GPL-2.0
Requires: flake8-deprecated-license = %{version}-%{release}
Requires: flake8-deprecated-python = %{version}-%{release}
Requires: flake8-deprecated-python3 = %{version}-%{release}
Requires: flake8
BuildRequires : buildreq-distutils3
BuildRequires : flake8
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
.. -*- coding: utf-8 -*-

.. image:: https://travis-ci.org/gforcada/flake8-deprecated.svg?branch=master
   :target: https://travis-ci.org/gforcada/flake8-deprecated

.. image:: https://coveralls.io/repos/gforcada/flake8-deprecated/badge.svg?branch=master&service=github
   :target: https://coveralls.io/github/gforcada/flake8-deprecated?branch=master

Flake8 deprecations plugin
==========================
No language, library or framework ever get everything right from the very beginning.
The project evolves, new features are added/changed/removed.

This means that projects relying on them must keep an eye on what's currently best practices.

This flake8 plugin helps you keeping up with method deprecations ans giving hints about what
they should be replaced with.

This plugin is based on a python checker that was in `plone.recipe.codeanalysis`_.

Install
-------
Install with pip::

    $ pip install flake8-deprecated

Requirements
------------
- Python 2.7, 3.5, 3.6
- flake8

TODO
----
- add a way to provide more deprecations on a per user basis(?), other plugins(?)
- add a way to ignore specific deprecations

License
-------
GPL 2.0

.. _`plone.recipe.codeanalysis`: https://pypi.python.org/pypi/plone.recipe.codeanalysis

.. -*- coding: utf-8 -*-

Changelog
=========

1.3 (2017-10-31)
----------------

- Fix flake8 errors on this package and enforce them on CI.
  [alexmuller]

1.2.2.dev0 (2017-10-22)
-----------------------

- Use the ast module to parse the code and ensure no false positives are found.
  [alexmuller]

1.2.1 (2017-07-24)
------------------
- Fix UnicodeDecodeError if system locale is not UTF-8.
  [sshishov]

1.2 (2017-05-12)
----------------
- added support for sublimetext (stdin/filename handling).
  [iham]

- Release as universal wheels.
  [gforcada]

- Only test against Python 2.7, 3.5 and 3.6.
  It most probably works on earlier versions of 2.x and 3.x but it's pointless to test on them as well.
  [gforcada]

1.1 (2016-10-26)
----------------
- Fix compatibility with flake8 3.
  [gforcada]

- Require flake8 > 3.0.
  [gforcada]

1.0 (2016-02-27)
----------------
- Warn if using xmlconfig.file, self.loadZCML is the preferred option.
  [gforcada]

- Avoid false reports by suffixing an opening parenthesis on all methods.
  [gforcada]

- Add decorators from zope.interface and zope.component.
  [gforcada]

0.2 (2016-01-20)
----------------
- Suggest to use AccessControl and zope.interface decorators.
  [gforcada]

0.1 (2015-09-17)
----------------
- Initial release.
  [gforcada]

- Create the flake8 plugin per se.
  [gforcada]

%package license
Summary: license components for the flake8-deprecated package.
Group: Default

%description license
license components for the flake8-deprecated package.


%package python
Summary: python components for the flake8-deprecated package.
Group: Default
Requires: flake8-deprecated-python3 = %{version}-%{release}

%description python
python components for the flake8-deprecated package.


%package python3
Summary: python3 components for the flake8-deprecated package.
Group: Default
Requires: python3-core
Provides: pypi(flake8-deprecated)

%description python3
python3 components for the flake8-deprecated package.


%prep
%setup -q -n flake8-deprecated-1.3
cd %{_builddir}/flake8-deprecated-1.3

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582923842
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/flake8-deprecated
cp %{_builddir}/flake8-deprecated-1.3/LICENSE %{buildroot}/usr/share/package-licenses/flake8-deprecated/4cc77b90af91e615a64ae04893fdffa7939db84c
cp %{_builddir}/flake8-deprecated-1.3/LICENSE.rst %{buildroot}/usr/share/package-licenses/flake8-deprecated/0c6f5260da599c2ea1bbe3b8b16e171332a14503
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/flake8-deprecated/0c6f5260da599c2ea1bbe3b8b16e171332a14503
/usr/share/package-licenses/flake8-deprecated/4cc77b90af91e615a64ae04893fdffa7939db84c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
